services:
  postgres:
    image: postgres:15-alpine
    container_name: fakturera-postgres
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - fakturera_db_data:/var/lib/postgresql/data

volumes:
  fakturera_db_data: